swagger: "2.0"
info:
  title: Faster
  description: APIs for Faster services.
  version: 1.0.0
host: localhost:8000
basePath: /api
schemes:
  - http

paths:
  /userDetails:
    post:
      tags:
        - "userDetails"
      summary: "Create userDetails"
      description: "Create userDetails"

      x-swagger-router-controller: "userController"
      operationId: createUserDetailsController

      consumes:
        - "application/json"
      produces:
        - "application/json"

      parameters:
        - in: body
          name: body
          description: payload
          required: true
          schema:
            $ref: "#/definitions/userDetails"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/ApiResponse"
        default:
          description: error
          schema:
            $ref: "#/definitions/ErrorResponse"

    get:
      tags:
        - "userDetails"
      summary: "Get userDetails"
      description: "Get userDetails"

      x-swagger-router-controller: "userController"
      operationId: getUserDetailsController

      consumes:
        - "application/json"
      produces:
        - "application/json"

      parameters:
        - in: query
          name: searchKey
          type: string
          required: true
          description: searchKey
        # - in: query
        #   name: phone
        #   type: string
        #   required: false
        #   description: phone
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/ApiResponse"
        default:
          description: error
          schema:
            $ref: "#/definitions/ErrorResponse"

    patch:
      tags:
        - "userDetails"
      summary: "update userDetails"
      description: "update userDetails"

      x-swagger-router-controller: "userController"
      operationId: updateUserDetailsController

      consumes:
        - "application/json"
      produces:
        - "application/json"

      parameters:
        - in: query
          name: searchKey
          type: string
          required: true
          description: searchKey
        - in: body
          name: body
          description: payload
          required: true
          schema:
            $ref: "#/definitions/userDetails"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/ApiResponse"
        default:
          description: error
          schema:
            $ref: "#/definitions/ErrorResponse"

    delete:
      tags:
        - "userDetails"
      summary: "delete userDetails"
      description: "delete userDetails"

      x-swagger-router-controller: "userController"
      operationId: deleteUserDetailsController

      consumes:
        - "application/json"
      produces:
        - "application/json"

      parameters:
        - in: query
          name: searchKey
          type: string
          required: true
          description: searchKey
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/ApiResponse"
        default:
          description: error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /Provider:
    post:
      tags:
        - "provider"
      summary: "create provider details"
      description: "create provider details"

      x-swagger-router-controller: "providerController"
      operationId: createprovidercontroller

      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: body
          name: body
          description: payload
          required: true
          schema:
            $ref: "#/definitions/provider"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/ApiResponse"
        default:
          description: error
          schema:
            $ref: "#/definitions/ErrorResponse"
    get:
      tags:
        - "provider"
      summary: "get provider details"
      description: "get provider details"
      x-swagger-router-controller: "providerController"
      operationId: getprovidercontroller
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: query
          name: searchkey
          description: "searchkey"
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/ApiResponse"
        default:
          description: error
          schema:
            $ref: "#/definitions/ErrorResponse"

    delete:
      tags:
        - "provider"
      summary: "delete the provider data"
      description: "delete provider details"
      x-swagger-router-controller: "providerController"
      operationId: deleteprovidercontroller
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: searchkey
          in: query
          required: true
          type: string
          description: "searchkey"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/ApiResponse"
        default:
          description: error
          schema:
            $ref: "#/definitions/ErrorResponse"
    patch:
      tags:
        - "provider"
      summary: "update the provider data"
      description: "update the provider data"
      x-swagger-router-controller: "providerController"
      operationId: updateprovidercontroller
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: email
          in: query
          required: true
          type: string
          description: "email"
        - in: body
          name: body
          description: payload
          required: true
          schema:
            $ref: "#/definitions/provider"
      responses:
        "200":
          description: success
          schema:
            $ref: "#/definitions/ApiResponse"
        default:
          description: error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /login/provider:
    post:
      tags:
        - "login"
      summary: "providerlogin"
      description: "login for provider"
      x-swagger-router-controller: "providerController"
      operationId: "generateProviderLoginTokenController"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: body
          name: username
          description: LoginCredentials
          required: true
          schema:
            $ref: "#/definitions/loginapi"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/ApiResponse"
        default:
          description: error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /login/user:
    post:
      tags:
        - "login"
      summary: "providerlogin"
      description: "login for provider"
      x-swagger-router-controller: "userController"
      operationId: "generateUserTokenController"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: body
          name: username
          description: LoginCredentials
          required: true
          schema:
            $ref: "#/definitions/loginapi"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/ApiResponse"
        default:
          description: error
          schema:
            $ref: "#/definitions/ErrorResponse"

definitions:
  SampleAPi:
    type: object

  provider:
    type: object
    properties:
      username:
        type: string
      firstname:
        type: string
      lastname:
        type: string
      email:
        type: string
      personalphnumber:
        type: string
      password:
        type: string
      personaladdress:
        type: string
      workphnumber:
        type: string
      workaddress:
        type: string
      StarRating:
        type: number
      role:
        type: string
      active:
        type: boolean

  userDetails:
    type: object
    properties:
      userName:
        type: string
      email:
        type: string
      password:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      userAddress:
        type: array
        items:
          type: object
      location:
        type: object
      lastSeen:
        type: string
      phone:
        type: string
      active:
        type: boolean

  loginapi:
    type: object
    required:
      - username
      - password
    properties:
      username:
        type: string
      password:
        type: string

  ApiResponse:
    type: object
    properties:
      code:
        type: integer
        format: int32
      data:
        type: object
    example:
      code: 0
      data: { "response": "api response Data" }

  ErrorResponse:
    type: object
    properties:
      code:
        type: integer
        format: int32
